apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-weip
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0011-tenant/tkrw-pr714-0075-0011-app/devfile-sample-weip@sha256:747653397e8145c302294d50750858e72f08ccab9b4bbafee9ebbcd6b00b40ce
        name: my-nodejs
        resources: {}
status: {}
